# GitHub Pages configuration for Ed-Toolkit
title: Ed-Toolkit
description: Essential developer tools for macOS with full accessibility support
url: "https://YOUR_USERNAME.github.io"
baseurl: "/ed-toolkit"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
author: Ed-Toolkit Team
social:
  name: Ed-Toolkit
  links:
    - https://github.com/YOUR_USERNAME/ed-toolkit

# Google Analytics (optional)
# google_analytics: G-XXXXXXXXXX